defaults: &defaults
  CONSUMER_KEY: 'M9fk94R9Gk3RkMJn4yJnr7u5S' # API KEY
  CONSUMER_SECRET: 'e2XkzNqI6JICtWQ5KIphbh4B5zhwPHDRLDnLp5BIF1sagFeLKz' #API KEY SECRET
  ACCESS_TOKEN: '1549763054761656321-dfd0uwvjrCpgIFvTcydZHq9jSwHdxe'
  ACCESS_TOKEN_SECRET: '9NR3h3M4i7RIhA2Czn9AYfLGfPD1Wyax5ihWw5DWofIqf'
  BEARER_TOKEN: 'AAAAAAAAAAAAAAAAAAAAABcpfAEAAAAAmPwgAE0B29F60r1TDLGjMHRFdtw%3D49zPIYgdJ3NzwwuxrvzyE6D05ITWLtpjSbsVyMY5ccrswPMNaI'

production: 
  <<: *defaults


    CONSUMER_KEY: 'M9fk94R9Gk3RkMJn4yJnr7u5S' # API KEY
  CONSUMER_SECRET: ‘e2XkzNqI6JICtWQ5KIphbh4B5zhwPHDRLDnLp5BIF1sagFeLKz’ #API KEY SECRET
  ACCESS_TOKEN: '1549763054761656321-dfd0uwvjrCpgIFvTcydZHq9jSwHdxe'
  ACCESS_TOKEN_SECRET: '9NR3h3M4i7RIhA2Czn9AYfLGfPD1Wyax5ihWw5DWofIqf'
  BEARER_TOKEN: 'AAAAAAAAAAAAAAAAAAAAABcpfAEAAAAAmPwgAE0B29F60r1TDLGjMHRFdtw%3D49zPIYgdJ3NzwwuxrvzyE6D05ITWLtpjSbsVyMY5ccrswPMNaI'